import type {
  Staff,
  Service,
  Customer,
  Appointment,
  Invoice,
  InventoryItem,
} from "@/lib/types";

export const salon = {
  name: "Aura Salon & Spa",
  address: "14 Lakeview Road, Civil Lines, Farrukhabad, UP 209625",
  phone: "+91 98765 43210",
  email: "hello@aurasalon.in",
  gstin: "09ABCDE1234F1Z5",
  whatsapp: "https://wa.me/919876543210",
  instagram: "https://instagram.com/aurasalonspa",
};

export const staff: Staff[] = [
  {
    id: "stf_1",
    name: "Priya Sharma",
    role: "Senior Stylist",
    avatarColor: "#D4AF37",
    phone: "+91 90011 22334",
    email: "priya@aurasalon.in",
    workingHours: "10:00 AM – 7:00 PM",
    skills: ["Haircut", "Hair Color", "Styling"],
    rating: 4.9,
    utilization: 88,
    revenueGenerated: 186400,
    commissionRate: 18,
    status: "ACTIVE",
  },
  {
    id: "stf_2",
    name: "Rohan Mehta",
    role: "Barber & Grooming Expert",
    avatarColor: "#1D5B8C",
    phone: "+91 90022 33445",
    email: "rohan@aurasalon.in",
    workingHours: "10:00 AM – 7:00 PM",
    skills: ["Haircut", "Beard Styling", "Shave"],
    rating: 4.8,
    utilization: 76,
    revenueGenerated: 134200,
    commissionRate: 15,
    status: "ACTIVE",
  },
  {
    id: "stf_3",
    name: "Ananya Iyer",
    role: "Esthetician",
    avatarColor: "#2F6F4E",
    phone: "+91 90033 44556",
    email: "ananya@aurasalon.in",
    workingHours: "11:00 AM – 8:00 PM",
    skills: ["Facial", "Skin Treatment", "Makeup"],
    rating: 4.95,
    utilization: 91,
    revenueGenerated: 211800,
    commissionRate: 20,
    status: "ACTIVE",
  },
  {
    id: "stf_4",
    name: "Kabir Singh",
    role: "Junior Stylist",
    avatarColor: "#A8412B",
    phone: "+91 90044 55667",
    email: "kabir@aurasalon.in",
    workingHours: "10:00 AM – 6:00 PM",
    skills: ["Haircut", "Hair Spa"],
    rating: 4.6,
    utilization: 58,
    revenueGenerated: 72300,
    commissionRate: 12,
    status: "ON_LEAVE",
  },
];

export const services: Service[] = [
  { id: "svc_1", name: "Classic Haircut", category: "Hair", durationMinutes: 30, price: 400, assignedStaffIds: ["stf_1", "stf_2", "stf_4"] },
  { id: "svc_2", name: "Beard Styling", category: "Grooming", durationMinutes: 20, price: 250, assignedStaffIds: ["stf_2"] },
  { id: "svc_3", name: "Hair Color – Global", category: "Hair", durationMinutes: 90, price: 2200, assignedStaffIds: ["stf_1"] },
  { id: "svc_4", name: "Signature Facial", category: "Skin", durationMinutes: 60, price: 1800, assignedStaffIds: ["stf_3"] },
  { id: "svc_5", name: "Bridal Makeup", category: "Makeup", durationMinutes: 120, price: 8500, assignedStaffIds: ["stf_3"] },
  { id: "svc_6", name: "Hair Spa & Treatment", category: "Hair", durationMinutes: 45, price: 1200, assignedStaffIds: ["stf_1", "stf_4"] },
  { id: "svc_7", name: "Express Manicure", category: "Nails", durationMinutes: 30, price: 500, assignedStaffIds: ["stf_3"] },
];

export const customers: Customer[] = [
  {
    id: "cus_1",
    name: "Neha Kapoor",
    phone: "+91 98110 23456",
    email: "neha.kapoor@gmail.com",
    birthday: "03-14",
    joinedAt: "2024-02-10",
    totalVisits: 23,
    totalSpend: 48600,
    loyaltyPoints: 486,
    lastVisit: "2026-06-20",
    notes: "Prefers Priya for color. Allergic to ammonia-based dyes.",
    tags: ["VIP", "Regular"],
  },
  {
    id: "cus_2",
    name: "Arjun Verma",
    phone: "+91 98220 34567",
    email: "arjun.verma@outlook.com",
    birthday: "11-02",
    joinedAt: "2025-08-05",
    totalVisits: 6,
    totalSpend: 5400,
    loyaltyPoints: 54,
    lastVisit: "2026-06-18",
    notes: "Usually books Sunday mornings.",
    tags: ["Regular"],
  },
  {
    id: "cus_3",
    name: "Simran Bhatia",
    phone: "+91 98330 45678",
    email: "simran.b@yahoo.com",
    birthday: "07-22",
    joinedAt: "2026-05-30",
    totalVisits: 1,
    totalSpend: 1800,
    loyaltyPoints: 18,
    lastVisit: "2026-05-30",
    notes: "First visit — facial. Interested in monthly skin package.",
    tags: ["New"],
  },
  {
    id: "cus_4",
    name: "Vikram Chauhan",
    phone: "+91 98440 56789",
    email: "vikram.c@gmail.com",
    birthday: "01-09",
    joinedAt: "2023-11-12",
    totalVisits: 41,
    totalSpend: 92300,
    loyaltyPoints: 923,
    lastVisit: "2026-04-02",
    notes: "Hasn't visited in 80+ days — send win-back offer.",
    tags: ["VIP", "At risk"],
  },
  {
    id: "cus_5",
    name: "Ritika Joshi",
    phone: "+91 98550 67890",
    email: "ritika.joshi@gmail.com",
    birthday: "09-18",
    joinedAt: "2025-12-01",
    totalVisits: 9,
    totalSpend: 16200,
    loyaltyPoints: 162,
    lastVisit: "2026-06-22",
    notes: "Booking bridal trial next month.",
    tags: ["Regular"],
  },
];

const today = "2026-06-25";
const t = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
};

export const appointments: Appointment[] = [
  { id: "apt_1", customerId: "cus_1", customerName: "Neha Kapoor", customerPhone: "+91 98110 23456", staffId: "stf_1", staffName: "Priya Sharma", serviceId: "svc_3", serviceName: "Hair Color – Global", date: today, time: "10:00", durationMinutes: 90, price: 2200, status: "CONFIRMED" },
  { id: "apt_2", customerId: "cus_2", customerName: "Arjun Verma", customerPhone: "+91 98220 34567", staffId: "stf_2", staffName: "Rohan Mehta", serviceId: "svc_2", serviceName: "Beard Styling", date: today, time: "11:00", durationMinutes: 20, price: 250, status: "COMPLETED" },
  { id: "apt_3", customerId: "cus_3", customerName: "Simran Bhatia", customerPhone: "+91 98330 45678", staffId: "stf_3", staffName: "Ananya Iyer", serviceId: "svc_4", serviceName: "Signature Facial", date: today, time: "12:30", durationMinutes: 60, price: 1800, status: "PENDING" },
  { id: "apt_4", customerId: "cus_5", customerName: "Ritika Joshi", customerPhone: "+91 98550 67890", staffId: "stf_3", staffName: "Ananya Iyer", serviceId: "svc_5", serviceName: "Bridal Makeup", date: today, time: "14:00", durationMinutes: 120, price: 8500, status: "CONFIRMED" },
  { id: "apt_5", customerId: "cus_4", customerName: "Vikram Chauhan", customerPhone: "+91 98440 56789", staffId: "stf_1", staffName: "Priya Sharma", serviceId: "svc_1", serviceName: "Classic Haircut", date: today, time: "16:00", durationMinutes: 30, price: 400, status: "PENDING" },
  { id: "apt_6", customerId: "cus_1", customerName: "Neha Kapoor", customerPhone: "+91 98110 23456", staffId: "stf_1", staffName: "Priya Sharma", serviceId: "svc_6", serviceName: "Hair Spa & Treatment", date: t(1), time: "11:00", durationMinutes: 45, price: 1200, status: "CONFIRMED" },
  { id: "apt_7", customerId: "cus_2", customerName: "Arjun Verma", customerPhone: "+91 98220 34567", staffId: "stf_4", staffName: "Kabir Singh", serviceId: "svc_1", serviceName: "Classic Haircut", date: t(1), time: "15:30", durationMinutes: 30, price: 400, status: "PENDING" },
  { id: "apt_8", customerId: "cus_5", customerName: "Ritika Joshi", customerPhone: "+91 98550 67890", staffId: "stf_3", staffName: "Ananya Iyer", serviceId: "svc_7", serviceName: "Express Manicure", date: t(2), time: "13:00", durationMinutes: 30, price: 500, status: "CONFIRMED" },
  { id: "apt_9", customerId: "cus_4", customerName: "Vikram Chauhan", customerPhone: "+91 98440 56789", staffId: "stf_2", staffName: "Rohan Mehta", serviceId: "svc_2", serviceName: "Beard Styling", date: t(-1), time: "17:00", durationMinutes: 20, price: 250, status: "CANCELLED" },
  { id: "apt_10", customerId: "cus_3", customerName: "Simran Bhatia", customerPhone: "+91 98330 45678", staffId: "stf_1", staffName: "Priya Sharma", serviceId: "svc_3", serviceName: "Hair Color – Global", date: t(3), time: "10:30", durationMinutes: 90, price: 2200, status: "CONFIRMED" },
];

export const invoices: Invoice[] = [
  {
    id: "inv_1",
    invoiceNumber: "AUR-2026-0142",
    customerId: "cus_2",
    customerName: "Arjun Verma",
    date: today,
    items: [{ serviceName: "Beard Styling", qty: 1, price: 250 }],
    subtotal: 250,
    discount: 0,
    tax: 13,
    total: 263,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    emailSent: true,
  },
  {
    id: "inv_2",
    invoiceNumber: "AUR-2026-0141",
    customerId: "cus_1",
    customerName: "Neha Kapoor",
    date: t(-1),
    items: [
      { serviceName: "Hair Color – Global", qty: 1, price: 2200 },
      { serviceName: "Hair Spa & Treatment", qty: 1, price: 1200 },
    ],
    subtotal: 3400,
    discount: 200,
    tax: 160,
    total: 3360,
    paymentStatus: "PAID",
    paymentMethod: "CREDIT_CARD",
    emailSent: true,
  },
  {
    id: "inv_3",
    invoiceNumber: "AUR-2026-0140",
    customerId: "cus_4",
    customerName: "Vikram Chauhan",
    date: t(-2),
    items: [{ serviceName: "Classic Haircut", qty: 1, price: 400 }],
    subtotal: 400,
    discount: 0,
    tax: 20,
    total: 420,
    paymentStatus: "PARTIAL",
    paymentMethod: "CASH",
    emailSent: false,
  },
  {
    id: "inv_4",
    invoiceNumber: "AUR-2026-0139",
    customerId: "cus_5",
    customerName: "Ritika Joshi",
    date: t(-3),
    items: [{ serviceName: "Express Manicure", qty: 1, price: 500 }],
    subtotal: 500,
    discount: 0,
    tax: 25,
    total: 525,
    paymentStatus: "PENDING",
    paymentMethod: "UPI",
    emailSent: true,
  },
];

export const inventory: InventoryItem[] = [
  { id: "inv_item_1", name: "Ammonia-Free Hair Color (Brown)", category: "Hair Color", quantity: 4, unit: "tubes", reorderLevel: 8, supplier: "L'Oréal Professionnel", costPerUnit: 420 },
  { id: "inv_item_2", name: "Keratin Shampoo 1L", category: "Hair Care", quantity: 12, unit: "bottles", reorderLevel: 6, supplier: "Schwarzkopf", costPerUnit: 650 },
  { id: "inv_item_3", name: "Disposable Razors", category: "Grooming", quantity: 22, unit: "packs", reorderLevel: 10, supplier: "Gillette Pro", costPerUnit: 180 },
  { id: "inv_item_4", name: "Facial Sheet Masks", category: "Skin", quantity: 5, unit: "boxes", reorderLevel: 6, supplier: "Lotus Herbals", costPerUnit: 320 },
  { id: "inv_item_5", name: "Nail Polish Set", category: "Nails", quantity: 18, unit: "sets", reorderLevel: 5, supplier: "Lakmé", costPerUnit: 240 },
  { id: "inv_item_6", name: "Bleach Powder 500g", category: "Hair Color", quantity: 3, unit: "packs", reorderLevel: 5, supplier: "Wella Professionals", costPerUnit: 510 },
];

// Pre-aggregated analytics for charts (would be DB aggregations in production)
export const revenueTrend = [
  { day: "Mon", revenue: 18400 },
  { day: "Tue", revenue: 15200 },
  { day: "Wed", revenue: 21800 },
  { day: "Thu", revenue: 19600 },
  { day: "Fri", revenue: 26300 },
  { day: "Sat", revenue: 38900 },
  { day: "Sun", revenue: 31200 },
];

export const monthlyRevenue = [
  { month: "Jan", revenue: 412000 },
  { month: "Feb", revenue: 438000 },
  { month: "Mar", revenue: 461000 },
  { month: "Apr", revenue: 449000 },
  { month: "May", revenue: 502000 },
  { month: "Jun", revenue: 538000 },
];

export const servicePerformance = [
  { name: "Hair Color", revenue: 186000, bookings: 84 },
  { name: "Haircut", revenue: 142000, bookings: 355 },
  { name: "Facial", revenue: 118000, bookings: 66 },
  { name: "Makeup", revenue: 96000, bookings: 11 },
  { name: "Hair Spa", revenue: 71000, bookings: 59 },
  { name: "Manicure", revenue: 38000, bookings: 76 },
];

export const peakHours = [
  { hour: "10am", bookings: 8 },
  { hour: "11am", bookings: 14 },
  { hour: "12pm", bookings: 18 },
  { hour: "1pm", bookings: 12 },
  { hour: "2pm", bookings: 16 },
  { hour: "3pm", bookings: 22 },
  { hour: "4pm", bookings: 26 },
  { hour: "5pm", bookings: 30 },
  { hour: "6pm", bookings: 24 },
  { hour: "7pm", bookings: 15 },
];

export const dashboardStats = {
  todayRevenue: 13013,
  todayBookings: 5,
  activeCustomers: 312,
  monthlyEarnings: 538000,
  monthGrowthPct: 7.2,
  retentionRate: 68,
};
